version: 0.2
phases:
  build:
    commands:
      - "find . -name '*.js' -exec mv {} . \\;"
      - aws cloudformation package --template-file sam.yml --s3-bucket aws-nmzl-lambda-transform
                                   --output-template-file outputSam.yml
artifacts:
  type: zip
  files:
    - sam.yml
    - outputSam.yml