AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Pipeline using CodePipeline, CodeBuild and CloudFormation for continuous delivery of a set of Lambda functions.
Parameters:
  TransformBucketName:
    Type: String
    Description: Transform Bucket Name
    Default: aws-nmzl-lambda-transform
  GitHubUser:
    Type: String
    Description: GitHub User
    Default: jackjinke
  GitHubRepo:
    Type: String
    Description: GitHub Repo to pull from. Only the Name. not the URL
    Default: nmzl-lambda
  GitHubBranch:
    Type: String
    Description: GitHub Branch
    Default: master
  GitHubToken:
    NoEcho: true
    Type: String
    Description: >-
      Secret. Go to https://github.com/settings/tokens
  BuildType:
    Type: String
    Default: LINUX_CONTAINER
    Description: The build container type to use for building the app
  BuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
    Description: The build compute type to use for building the app
  BuildImage:
    Type: String
    Default: 'aws/codebuild/ubuntu-base:14.04'
    Description: The build image to use for building the app

  SteamApiKey:
    NoEcho: true
    Type: String
    Description: >-
      Secret. Go to https://steamcommunity.com/dev/apikey
    Default: ''
  OpenDotaApiKey:
    NoEcho: true
    Type: String
    Description: >-
      Secret. Go to https://www.opendota.com/api-keys
    Default: ''
  TeamPlayerCountThreshold:
    Type: Number
    Description: Team player count threshold to mark a matches as a valid team match
    Default: 3
  GetPlayersLambdaCacheTTL:
    Type: Number
    Description: Cache TTL for GetPlayers Lambda function
    Default: 120
  GetPlayersLambdaSignatureHeroCountThreshold:
    Type: Number
    Description: Hero count threshold for calculating signature hero in GetPlayers Lambda function
    Default: 3
  GetPlayersLambdaSignatureHeroMatchLimit:
    Type: Number
    Description: Match limit for calculating signature hero in GetPlayers Lambda function
    Default: 150
  GetBattleCupMatchesLambdaCacheTTL:
    Type: Number
    Description: Cache TTL for GetBattleCupMatches Lambda function
    Default: 120
  GetHeroMetadataLambdaCacheTTL:
    Type: Number
    Description: Cache TTL for GetHeroMetadata Lambda function
    Default: 3600
  RefreshPlayersOpendotaProfileScheduleExpression:
    Type: String
    Description: Schedule expression for RefreshPlayersOpendotaProfile Lambda function
    Default: 'cron(0 9 * * ? *)'
  LoadMatchesScheduleExpression:
    Type: String
    Description: Schedule expression for LoadMatches Lambda function
    Default: 'cron(0 10 * * ? *)'
  RefreshAllMatchIdsScheduleExpression:
    Type: String
    Description: Schedule expression for RefreshAllMatchIds Lambda function
    Default: 'cron(0 9 ? * SAT *)'
  AllMatchIdsCacheTTL:
    Type: Number
    Description: Cache TTL for All MatchIds
    Default: 129600 
  UpdateHeroMetadataScheduleExpression:
    Type: String
    Description: Schedule expression for UpdateHeroMetadata Lambda function
    Default: 'rate(1 day)'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: SAM Configuration
        Parameters:
        - TransformBucketName
      - Label:
          default: GitHub Configuration
        Parameters:
        - GitHubToken
        - GitHubUser
        - GitHubRepo
        - GitHubBranch
      - Label:
          default: Build Configuration
        Parameters:
        - BuildType
        - BuildComputeType
        - BuildImage
      - Label:
          default: Dota APIs Configuration
        Parameters:
        - SteamApiKey
        - OpenDotaApiKey
      - Label:
          default: General configuration
        Parameters:
        - TeamPlayerCountThreshold
      - Label:
          default: GetPlayers Configuration
        Parameters:
        - GetPlayersLambdaCacheTTL
        - GetPlayersLambdaSignatureHeroCountThreshold
        - GetPlayersLambdaSignatureHeroMatchLimit
      - Label:
          default: GetBattleCupMatches Configuration
        Parameters:
        - GetBattleCupMatchesLambdaCacheTTL
      - Label:
          default: GetHeroMetadata Configuration
        Parameters:
        - GetHeroMetadataLambdaCacheTTL
      - Label:
          default: RefreshPlayersOpendotaProfile Configuration
        Parameters:
        - RefreshPlayersOpendotaProfileScheduleExpression
      - Label:
          default: LoadMatches Configuration
        Parameters:
        - LoadMatchesScheduleExpression
      - Label:
          default: RefreshAllMatchIds Configuration
        Parameters:
        - RefreshAllMatchIdsScheduleExpression
        - AllMatchIdsCacheTTL
      - Label:
          default: UpdateHeroMetadata Configuration
        Parameters:
        - UpdateHeroMetadataScheduleExpression
    ParameterLabels:
      GitHubToken:
        default: GitHub OAuth2 Token
      GitHubUser:
        default: GitHub User/Org Name
      GitHubRepo:
        default: GitHub Repository Name
      GitHubBranch:
        default: GitHub Branch Name
      BuildType:
        default: CodeBuild type
      BuildComputeType:
        default: CodeBuild instance type
      BuildImage:
        default: CodeBuild image
      SteamApiKey:
        default: Steam API Key
      OpenDotaApiKey:
        default: OpenDota API Key
      TeamPlayerCountThreshold:
        default: Team player count threshold
      GetPlayersLambdaCacheTTL:
        default: Cache TTL
      GetPlayersLambdaSignatureHeroCountThreshold:
        default: Hero count threshold
      GetPlayersLambdaSignatureHeroMatchLimit:
        default: Match limit
      GetBattleCupMatchesLambdaCacheTTL:
        default: Cache TTL
      GetHeroMetadataLambdaCacheTTL:
        default: Cache TTL
      RefreshPlayersOpendotaProfileScheduleExpression:
        default: Schedule expression
      LoadMatchesScheduleExpression:
        default: Schedule expression
      RefreshAllMatchIdsScheduleExpression:
        default: Schedule expression
      AllMatchIdsCacheTTL:
        default: Cache TTL
      UpdateHeroMetadataScheduleExpression:
        default: Schedule expression

Resources:
  TransformBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref TransformBucketName

  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
            - 'sts:AssumeRole'
      Path: /
      Policies:
      - PolicyName: codebuild-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - 'codebuild:*'
            - 'logs:*'
            - 's3:*'
            Resource: '*'
          Version: 2012-10-17

  CloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
          Action:
            - 'sts:AssumeRole'
      Path: /
      Policies:
      - PolicyName: cloudformation-service
        PolicyDocument:
          Statement:
          - Action: '*'
            Resource: '*'
            Effect: Allow
          Version: 2012-10-17

  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - codepipeline.amazonaws.com
          Action:
            - 'sts:AssumeRole'
      Path: /
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Statement:
          - Action:
              - 'codebuild:*'
              - 's3:*'
              - 'cloudformation:*'
              - 'iam:PassRole'
            Resource: '*'
            Effect: Allow

  PipelineBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete

  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    DependsOn: CodeBuildRole
    Properties:
      Name: !Sub '${AWS::StackName}-project'
      Description: 'CodeBuild project for nmzl-lambda'
      ServiceRole: !GetAtt
        - CodeBuildRole
        - Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref BuildType
        ComputeType: !Ref BuildComputeType
        Image: !Sub '${BuildImage}'
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: nmzl-lambda
      RoleArn: !GetAtt
        - CodePipelineRole
        - Arn
      Stages:
        - Name: Source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        - Name: Packaging
          Actions:
            - Name: Artifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: PackagingOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              InputArtifacts:
                - Name: PackagingOutput
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM
                StackName: 'nmzl-lambda-deploy'
                ChangeSetName: 'nmzl-lambda-deploy-changeset'
                TemplatePath: PackagingOutput::outputSam.yml
                ParameterOverrides: !Sub |
                  {
                    "SteamApiKey" : "${SteamApiKey}",
                    "OpenDotaApiKey" : "${OpenDotaApiKey}",
                    "GetPlayersLambdaCacheTTL" : "${GetPlayersLambdaCacheTTL}",
                    "GetPlayersLambdaSignatureHeroCountThreshold" : "${GetPlayersLambdaSignatureHeroCountThreshold}",
                    "GetPlayersLambdaSignatureHeroMatchLimit" : "${GetPlayersLambdaSignatureHeroMatchLimit}",
                    "GetBattleCupMatchesLambdaCacheTTL" : "${GetBattleCupMatchesLambdaCacheTTL}",
                    "TeamPlayerCountThreshold" : "${TeamPlayerCountThreshold}",
                    "GetHeroMetadataLambdaCacheTTL" : "${GetHeroMetadataLambdaCacheTTL}",
                    "RefreshPlayersOpendotaProfileScheduleExpression" : "${RefreshPlayersOpendotaProfileScheduleExpression}",
                    "LoadMatchesScheduleExpression" : "${LoadMatchesScheduleExpression}",
                    "RefreshAllMatchIdsScheduleExpression" : "${RefreshAllMatchIdsScheduleExpression}",
                    "AllMatchIdsCacheTTL" : "${AllMatchIdsCacheTTL}",
                    "UpdateHeroMetadataScheduleExpression" : "${UpdateHeroMetadataScheduleExpression}"
                  }
                RoleArn: !GetAtt
                - CloudFormationRole
                - Arn
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                Capabilities: CAPABILITY_IAM
                StackName: 'nmzl-lambda-deploy'
                ChangeSetName: 'nmzl-lambda-deploy-changeset'
              RunOrder: 2
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
Outputs:
  PipelineUrl:
    Value: !Sub >-
      https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
    Description: CodePipeline URL
